# Generated by Django 4.1.5 on 2023-01-22 11:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies_app', '0002_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='rating',
            field=models.SmallIntegerField(db_column='rating', default='0', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(11)]),
            preserve_default=False,
        ),
    ]
